#!/bin/python3

import math
import os
import random
import re
import sys



#
# Complete the 'dateandtime' function below.
#
# The function accepts INTEGER val as parameter.
# The return type must be LIST.
#
import datetime

def dateandtime(val,tup):
    # Write your code here
    lst = list()
    if val == 1 :
        lst.append(datetime.date(*tup))
        lst.append(lst[0].strftime("%d/%m/%Y"))
    elif val == 2:
        lst.append(datetime.date.fromtimestamp(*tup))
    elif val == 3:
        lst.append(datetime.time(*tup))
        lst.append(lst[0].strftime("%I"))
    elif val == 4:
        t=datetime.date(*tup)        
        lst.append("{0:%A}".format(t))
        lst.append("{0:%B}".format(t))
        lst.append(str(t.timetuple().tm_yday).zfill(3))
    elif val == 5:
        lst.append(datetime.datetime(*tup))
    return lst



if __name__ == '__main__':
    val = int(input().strip())
    
    if val ==1 or val==4 or val ==3:
        qw1_count=3
    if val==2:
        qw1_count=1
    if val ==5:
        qw1_count=6
    qw1 = []

    for _ in range(qw1_count):
        qw1_item = int(input().strip())
        qw1.append(qw1_item)
        
    tup=tuple(qw1)
    
    ans = dateandtime(val,tup)
    
    print(ans)
