#!/bin/python3

import math
import os
import random
import re
import sys



#
# Complete the 'strmethod' function below.
#
# The function accepts following parameters:
#  1. STRING para
#  2. STRING spch1
#  3. STRING spch2
#  4. LIST li1
#  5. STRING strf
#
def stringmethod(para, special1, special2, list1, strfind):
    # Write your code here
    word1=para
    for s in special1:
        word1=word1.replace(s,"")
    rword2=word1[69::-1]
    print(rword2)
    print(special2.join([i for i in rword2 if i != " "]))
    if "f" in ["t" if para.find(i)>0 else "f" for i in list1]:
        print(f"Every string in  {list1} were not present")
    else:
        print(f"Every string in  {list1} were present")
    print(word1.split()[:20])
    d=dict()
    for i in word1.split():
        if i in d.keys():
            d[i]+=1
        else:
            d[i]=1
    lst = list()
    for k in d:
        if d[k]<3:
            lst.append(k)
    print(lst[-20::1])            
    print(word1.rindex(strfind))

if __name__ == '__main__':
